services:
  postgres:
    image: postgres:15-alpine
    ports:
      - 5432:5432  # enables connecting locally via psql
    environment:
      POSTGRES_DB: myblog
      POSTGRES_USER: postgres  # Replace with your desired username
      POSTGRES_PASSWORD: mypassword